title: Welcome to My New Blog! 
author: Nina
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Nina's Github Learning Lab blog! 

# social links
github_username:  nmc1313 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
